version: '3.8'

services:
  trusttea-bot:
    build: .
    container_name: trusttea-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SENDGRID_TOKEN=${SENDGRID_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    restart: unless-stopped
    entrypoint: ["bun", "run", "src/index.ts"]