version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "Tea"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  trusttea-bot:
    build: .
    container_name: trusttea-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SENDGRID_TOKEN=${SENDGRID_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    restart: unless-stopped
    entrypoint: ["bun", "run", "src/index.ts"]



volumes:
  postgres_data: